// Apify Integration Service
// Handles YouTube transcript extraction via Apify Actors

import type { TranscriptResult } from '../types/youtube';

// ============================================
// CONSTANTS
// ============================================

const APIFY_API_BASE = 'https://api.apify.com/v2';
const TRANSCRIPT_ACTOR_ID = 'streamers/youtube-transcript-scraper';

// Timing constants
const MAX_WAIT_TIME_MS = 120000; // 2 minutes max wait
const POLL_INTERVAL_MS = 5000;  // Check every 5 seconds
const DEFAULT_MAX_RETRIES = 3;

// ============================================
// TYPES
// ============================================

interface ApifyRunResponse {
  data: {
    id: string;
    status: string;
    actId: string;
    userId: string;
    startedAt: string;
    finishedAt?: string;
    buildId: string;
    buildNumber: string;
    exitCode?: number;
    defaultKeyValueStoreId: string;
    defaultDatasetId: string;
    defaultRequestQueueId: string;
  };
}

interface ApifyTranscriptItem {
  videoId: string;
  transcript: string;
  language: string;
  isAutoGenerated?: boolean;
}

interface ApifyAccountInfo {
  data: {
    id: string;
    username: string;
    plan: string;
    usedCredits?: number;
    availableCredits?: number;
  };
}

// ============================================
// CORE FUNCTIONS
// ============================================

/**
 * Extract YouTube video transcript using Apify Actor
 *
 * @param videoUrl - Full YouTube video URL (e.g., https://www.youtube.com/watch?v=xxxxx)
 * @param apifyApiKey - User's Apify API key
 * @returns TranscriptResult with transcript text or error
 */
export async function fetchTranscript(
  videoUrl: string,
  apifyApiKey: string
): Promise<TranscriptResult> {
  try {
    // Step 1: Start the Actor run
    const runResponse = await startActorRun(videoUrl, apifyApiKey);
    const runId = runResponse.data.id;

    // Step 2: Poll for completion
    const finalStatus = await pollRunStatus(runId, apifyApiKey);

    if (finalStatus !== 'SUCCEEDED') {
      return {
        success: false,
        transcript: null,
        language: null,
        is_auto_generated: false,
        error: `Apify run failed with status: ${finalStatus}`,
      };
    }

    // Step 3: Fetch the results
    const results = await fetchRunResults(runId, apifyApiKey);

    if (!results || results.length === 0) {
      return {
        success: false,
        transcript: null,
        language: null,
        is_auto_generated: false,
        error: 'No transcript found for this video. It may not have captions available.',
      };
    }

    const transcriptItem = results[0];

    if (!transcriptItem.transcript) {
      return {
        success: false,
        transcript: null,
        language: null,
        is_auto_generated: false,
        error: 'Transcript was empty. The video may not have captions enabled.',
      };
    }

    return {
      success: true,
      transcript: transcriptItem.transcript,
      language: transcriptItem.language || 'en',
      is_auto_generated: transcriptItem.isAutoGenerated ?? true,
    };
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    return {
      success: false,
      transcript: null,
      language: null,
      is_auto_generated: false,
      error: `Transcript extraction failed: ${errorMessage}`,
    };
  }
}

/**
 * Extract transcript with retry logic
 * Retries with exponential backoff on transient failures
 */
export async function fetchTranscriptWithRetry(
  videoUrl: string,
  apifyApiKey: string,
  maxRetries: number = DEFAULT_MAX_RETRIES
): Promise<TranscriptResult> {
  let lastResult: TranscriptResult | null = null;

  for (let attempt = 1; attempt <= maxRetries; attempt++) {
    const result = await fetchTranscript(videoUrl, apifyApiKey);

    // Success
    if (result.success) {
      return result;
    }

    lastResult = result;

    // Don't retry if it's a permanent failure (no captions)
    if (result.error?.includes('no captions') ||
        result.error?.includes('not have captions')) {
      return result;
    }

    // Don't retry on the last attempt
    if (attempt < maxRetries) {
      // Exponential backoff: 2s, 4s, 8s
      const backoffMs = Math.pow(2, attempt) * 1000;
      console.log(`Transcript fetch attempt ${attempt} failed, retrying in ${backoffMs}ms...`);
      await sleep(backoffMs);
    }
  }

  return lastResult || {
    success: false,
    transcript: null,
    language: null,
    is_auto_generated: false,
    error: 'Transcript extraction failed after all retries',
  };
}

// ============================================
// APIFY API HELPERS
// ============================================

/**
 * Start an Actor run
 */
async function startActorRun(videoUrl: string, apiKey: string): Promise<ApifyRunResponse> {
  const url = `${APIFY_API_BASE}/acts/${TRANSCRIPT_ACTOR_ID}/runs`;

  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      startUrls: [{ url: videoUrl }],
    }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Failed to start Apify run: ${response.status} - ${errorText}`);
  }

  return await response.json();
}

/**
 * Poll for run completion
 */
async function pollRunStatus(runId: string, apiKey: string): Promise<string> {
  const startTime = Date.now();
  let status = 'RUNNING';

  while (status === 'RUNNING' || status === 'READY') {
    // Check timeout
    if (Date.now() - startTime > MAX_WAIT_TIME_MS) {
      throw new Error('Apify run timed out');
    }

    await sleep(POLL_INTERVAL_MS);

    const response = await fetch(`${APIFY_API_BASE}/actor-runs/${runId}`, {
      headers: {
        'Authorization': `Bearer ${apiKey}`,
      },
    });

    if (!response.ok) {
      throw new Error(`Failed to check run status: ${response.status}`);
    }

    const data: ApifyRunResponse = await response.json();
    status = data.data.status;
  }

  return status;
}

/**
 * Fetch results from completed run
 */
async function fetchRunResults(runId: string, apiKey: string): Promise<ApifyTranscriptItem[]> {
  const url = `${APIFY_API_BASE}/actor-runs/${runId}/dataset/items`;

  const response = await fetch(url, {
    headers: {
      'Authorization': `Bearer ${apiKey}`,
    },
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch run results: ${response.status}`);
  }

  return await response.json();
}

// ============================================
// ACCOUNT & QUOTA MANAGEMENT
// ============================================

/**
 * Check Apify account info and quota
 * Returns available credits (useful for showing users their remaining quota)
 */
export async function checkApifyAccount(apiKey: string): Promise<{
  valid: boolean;
  username?: string;
  availableCredits?: number;
  error?: string;
}> {
  try {
    const response = await fetch(`${APIFY_API_BASE}/users/me`, {
      headers: {
        'Authorization': `Bearer ${apiKey}`,
      },
    });

    if (!response.ok) {
      if (response.status === 401) {
        return { valid: false, error: 'Invalid API key' };
      }
      return { valid: false, error: `API error: ${response.status}` };
    }

    const data: ApifyAccountInfo = await response.json();

    return {
      valid: true,
      username: data.data.username,
      availableCredits: data.data.availableCredits,
    };
  } catch (error) {
    return {
      valid: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    };
  }
}

/**
 * Validate that an API key is working
 */
export async function validateApifyKey(apiKey: string): Promise<boolean> {
  const result = await checkApifyAccount(apiKey);
  return result.valid;
}

// ============================================
// UTILITIES
// ============================================

/**
 * Sleep for specified milliseconds
 */
function sleep(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms));
}

/**
 * Estimate Apify credits needed for a transcript extraction
 * This is a rough estimate - actual usage depends on video length
 */
export function estimateCreditsNeeded(videoCount: number): number {
  // Rough estimate: 0.05 credits per video (may vary)
  return Math.ceil(videoCount * 0.05 * 100) / 100;
}

/**
 * Clean transcript text for better extraction
 * - Remove timing artifacts
 * - Normalize whitespace
 * - Remove speaker labels if present
 */
export function cleanTranscript(transcript: string): string {
  let cleaned = transcript;

  // Remove common timestamp patterns like [00:00:00] or (00:00)
  cleaned = cleaned.replace(/\[[\d:]+\]/g, '');
  cleaned = cleaned.replace(/\([\d:]+\)/g, '');

  // Remove speaker labels like "Speaker 1:" or "John:"
  cleaned = cleaned.replace(/^[A-Za-z\s]+\d*:\s*/gm, '');

  // Normalize whitespace
  cleaned = cleaned.replace(/\s+/g, ' ');
  cleaned = cleaned.replace(/\n\s*\n/g, '\n\n');

  return cleaned.trim();
}
