import React, { useEffect, useState } from 'react';
import { Sparkles, X, Lightbulb, Info, AlertTriangle, CheckCircle2 } from 'lucide-react';
import { TableRow, AnalysisResult } from '../types';
import { analyzeTableData } from '../services/gemini';
import clsx from 'clsx';

interface AIAnalystProps {
  tableName: string;
  data: TableRow[] | null;
  isOpen: boolean;
  onClose: () => void;
}

export const AIAnalyst: React.FC<AIAnalystProps> = ({ tableName, data, isOpen, onClose }) => {
  const [analysis, setAnalysis] = useState<AnalysisResult | null>(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (isOpen && data && data.length > 0) {
      setLoading(true);
      analyzeTableData(tableName, data)
        .then(setAnalysis)
        .finally(() => setLoading(false));
    }
  }, [isOpen, tableName, data]);

  if (!isOpen) return null;

  return (
    <div className="w-96 bg-white border-l border-slate-200 flex flex-col shadow-xl absolute right-0 top-0 bottom-0 z-20 transition-transform duration-300 transform translate-x-0">
      <div className="p-4 border-b border-slate-100 flex items-center justify-between bg-gradient-to-r from-indigo-50 to-white">
        <div className="flex items-center text-indigo-700">
          <Sparkles size={18} className="mr-2" />
          <h2 className="font-semibold">Gemini Insights</h2>
        </div>
        <button onClick={onClose} className="text-slate-400 hover:text-slate-600">
          <X size={18} />
        </button>
      </div>

      <div className="flex-1 overflow-y-auto p-6 space-y-6">
        {loading ? (
          <div className="space-y-4 animate-pulse">
            <div className="h-4 bg-slate-100 rounded w-3/4"></div>
            <div className="h-20 bg-slate-100 rounded"></div>
            <div className="h-20 bg-slate-100 rounded"></div>
          </div>
        ) : !data || data.length === 0 ? (
          <div className="text-center text-slate-500 mt-10">
            <p>No data available for analysis.</p>
          </div>
        ) : analysis ? (
          <>
            <div className="bg-slate-50 p-4 rounded-lg border border-slate-100">
              <h3 className="text-xs font-bold text-slate-500 uppercase tracking-wide mb-2">Summary</h3>
              <p className="text-sm text-slate-700 leading-relaxed">{analysis.summary}</p>
            </div>

            <div>
              <h3 className="text-xs font-bold text-slate-500 uppercase tracking-wide mb-3">Key Findings</h3>
              <div className="space-y-3">
                {analysis.insights.map((insight, idx) => (
                  <div key={idx} className={clsx(
                    "p-3 rounded-lg border text-sm",
                    insight.type === 'info' && "bg-blue-50 border-blue-100 text-blue-800",
                    insight.type === 'warning' && "bg-amber-50 border-amber-100 text-amber-800",
                    insight.type === 'success' && "bg-emerald-50 border-emerald-100 text-emerald-800",
                  )}>
                    <div className="flex items-start">
                      <div className="mt-0.5 mr-2 flex-shrink-0">
                        {insight.type === 'info' && <Info size={16} />}
                        {insight.type === 'warning' && <AlertTriangle size={16} />}
                        {insight.type === 'success' && <CheckCircle2 size={16} />}
                      </div>
                      <div>
                        <span className="font-semibold block mb-1">{insight.title}</span>
                        <span className="opacity-90">{insight.description}</span>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
            
            <div className="text-xs text-slate-400 text-center pt-4">
              Analysis generated by Google Gemini 2.0 Flash
            </div>
          </>
        ) : null}
      </div>
    </div>
  );
};
