// Vercel API endpoint for digest delivery to channels
// POST /api/digest/deliver
// Body: { history_id: string, channels?: string[] }
// Headers: Authorization: Bearer <jwt>

import type { VercelRequest, VercelResponse } from '@vercel/node';
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = process.env.SUPABASE_URL!;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY!;
const RESEND_API_KEY = process.env.RESEND_API_KEY;

const getSupabase = () => createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

// ─── Email Formatter ────────────────────────────────────────

function formatDigestEmail(content: any, profileName: string): { subject: string; html: string } {
  const date = new Date(content.generated_at).toLocaleDateString('en-GB', {
    weekday: 'long', day: 'numeric', month: 'long', year: 'numeric',
  });

  const subject = `Synapse ${content.frequency} Brief — ${date}`;

  const sectionsHtml = (content.sections || []).map((section: any) => `
    <div style="margin-bottom: 24px; padding: 16px; background: #161e2e; border-radius: 8px; border: 1px solid rgba(255,255,255,0.1);">
      <h3 style="margin: 0 0 12px 0; color: #a78bfa; font-size: 14px; font-weight: 600;">${section.module_name}</h3>
      ${section.highlights?.length > 0 ? `
        <ul style="margin: 0 0 12px 0; padding-left: 16px;">
          ${section.highlights.map((h: string) => `<li style="color: #e2e8f0; font-size: 13px; margin-bottom: 4px;">${h}</li>`).join('')}
        </ul>
      ` : ''}
      <div style="color: #94a3b8; font-size: 12px; line-height: 1.6; white-space: pre-wrap;">${section.content}</div>
    </div>
  `).join('');

  const stepsHtml = (content.suggested_next_steps || []).map((step: any, i: number) => `
    <div style="margin-bottom: 8px; display: flex; gap: 8px;">
      <span style="color: ${step.priority === 'high' ? '#f87171' : step.priority === 'medium' ? '#fbbf24' : '#34d399'}; font-size: 11px; font-weight: 700; text-transform: uppercase; min-width: 50px;">${step.priority}</span>
      <div>
        <span style="color: #e2e8f0; font-size: 13px; font-weight: 500;">${step.action}</span>
        <span style="color: #64748b; font-size: 11px; display: block;">${step.rationale}</span>
      </div>
    </div>
  `).join('');

  const html = `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head>
<body style="margin: 0; padding: 0; background: #02040a; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;">
  <div style="max-width: 600px; margin: 0 auto; padding: 32px 16px;">
    <!-- Header -->
    <div style="text-align: center; margin-bottom: 32px;">
      <h1 style="color: #22d3ee; font-size: 20px; margin: 0;">Synapse</h1>
      <p style="color: #64748b; font-size: 12px; margin: 4px 0 0 0;">${profileName} — ${date}</p>
    </div>

    <!-- Executive Summary -->
    <div style="padding: 20px; background: linear-gradient(135deg, rgba(34,211,238,0.1), rgba(139,92,246,0.1)); border: 1px solid rgba(34,211,238,0.2); border-radius: 12px; margin-bottom: 24px;">
      <p style="color: #22d3ee; font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 1px; margin: 0 0 8px 0;">Executive Summary</p>
      <p style="color: #e2e8f0; font-size: 14px; line-height: 1.6; margin: 0;">${content.executive_summary || ''}</p>
    </div>

    <!-- Sections -->
    ${sectionsHtml}

    <!-- Next Steps -->
    ${(content.suggested_next_steps || []).length > 0 ? `
    <div style="padding: 16px; background: #161e2e; border-radius: 8px; border: 1px solid rgba(255,255,255,0.1); margin-bottom: 24px;">
      <h3 style="margin: 0 0 12px 0; color: #fbbf24; font-size: 14px; font-weight: 600;">Suggested Next Steps</h3>
      ${stepsHtml}
    </div>
    ` : ''}

    <!-- Footer -->
    <div style="text-align: center; padding-top: 24px; border-top: 1px solid rgba(255,255,255,0.05);">
      <p style="color: #475569; font-size: 11px; margin: 0;">Generated by Synapse Orientation Engine</p>
    </div>
  </div>
</body>
</html>`;

  return { subject, html };
}

// ─── Send Email via Resend ──────────────────────────────────

async function sendEmail(to: string, subject: string, html: string): Promise<{ success: boolean; error?: string }> {
  if (!RESEND_API_KEY) {
    return { success: false, error: 'RESEND_API_KEY not configured' };
  }

  try {
    const response = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${RESEND_API_KEY}`,
      },
      body: JSON.stringify({
        from: process.env.RESEND_FROM_EMAIL || 'Synapse <onboarding@resend.dev>',
        to: [to],
        subject,
        html,
      }),
    });

    if (!response.ok) {
      const err = await response.text();
      return { success: false, error: `Resend API error: ${err}` };
    }

    return { success: true };
  } catch (error) {
    return { success: false, error: (error as Error).message };
  }
}

// ─── Telegram Formatter & Sender ─────────────────────────────

function formatDigestTelegram(content: any, profileName: string): string {
  const date = new Date(content.generated_at).toLocaleDateString('en-GB', {
    weekday: 'long', day: 'numeric', month: 'long',
  });

  let text = `*Synapse — ${profileName}*\n_${date}_\n\n`;
  text += `*Executive Summary*\n${content.executive_summary || 'N/A'}\n\n`;

  for (const section of (content.sections || [])) {
    if (section.content?.startsWith('Error')) continue;
    text += `*${section.module_name}*\n`;
    if (section.highlights?.length > 0) {
      for (const h of section.highlights) {
        text += `• ${h}\n`;
      }
    }
    text += '\n';
  }

  if (content.suggested_next_steps?.length > 0) {
    text += `*Next Steps*\n`;
    for (const step of content.suggested_next_steps) {
      text += `[${step.priority?.toUpperCase()}] ${step.action}\n`;
    }
  }

  return text;
}

async function sendTelegram(botToken: string, chatId: string, text: string): Promise<{ success: boolean; error?: string }> {
  try {
    const response = await fetch(`https://api.telegram.org/bot${botToken}/sendMessage`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        chat_id: chatId,
        text,
        parse_mode: 'Markdown',
        disable_web_page_preview: true,
      }),
    });
    if (!response.ok) {
      const err = await response.text();
      return { success: false, error: `Telegram API error: ${err}` };
    }
    return { success: true };
  } catch (error) {
    return { success: false, error: (error as Error).message };
  }
}

// ─── Slack Formatter & Sender ────────────────────────────────

function formatDigestSlack(content: any, profileName: string): any {
  const date = new Date(content.generated_at).toLocaleDateString('en-GB', {
    weekday: 'long', day: 'numeric', month: 'long',
  });

  const blocks: any[] = [
    {
      type: 'header',
      text: { type: 'plain_text', text: `Synapse — ${profileName}` },
    },
    {
      type: 'context',
      elements: [{ type: 'mrkdwn', text: `_${date}_` }],
    },
    { type: 'divider' },
    {
      type: 'section',
      text: { type: 'mrkdwn', text: `*Executive Summary*\n${content.executive_summary || 'N/A'}` },
    },
  ];

  for (const section of (content.sections || [])) {
    if (section.content?.startsWith('Error')) continue;
    let text = `*${section.module_name}*\n`;
    if (section.highlights?.length > 0) {
      text += section.highlights.map((h: string) => `• ${h}`).join('\n');
    }
    blocks.push({ type: 'section', text: { type: 'mrkdwn', text } });
  }

  if (content.suggested_next_steps?.length > 0) {
    blocks.push({ type: 'divider' });
    let stepsText = '*Next Steps*\n';
    for (const step of content.suggested_next_steps) {
      stepsText += `[${step.priority?.toUpperCase()}] ${step.action}\n`;
    }
    blocks.push({ type: 'section', text: { type: 'mrkdwn', text: stepsText } });
  }

  return { blocks };
}

async function sendSlack(webhookUrl: string, payload: any): Promise<{ success: boolean; error?: string }> {
  try {
    const response = await fetch(webhookUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    });
    if (!response.ok) {
      const err = await response.text();
      return { success: false, error: `Slack webhook error: ${err}` };
    }
    return { success: true };
  } catch (error) {
    return { success: false, error: (error as Error).message };
  }
}

// ─── Handler ────────────────────────────────────────────────

export default async function handler(req: VercelRequest, res: VercelResponse) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  // Auth
  const authHeader = req.headers.authorization;
  if (!authHeader?.startsWith('Bearer ')) {
    return res.status(401).json({ error: 'Missing authorization' });
  }
  const jwt = authHeader.slice(7);
  const supabase = getSupabase();
  const { data: { user }, error: authError } = await supabase.auth.getUser(jwt);
  if (authError || !user) return res.status(401).json({ error: 'Invalid token' });

  const { history_id, channels: channelFilter } = req.body;
  if (!history_id) return res.status(400).json({ error: 'history_id required' });

  try {
    // Load digest history entry
    const { data: entry, error: entryError } = await supabase
      .from('digest_history')
      .select('*')
      .eq('id', history_id)
      .eq('user_id', user.id)
      .single();

    if (entryError || !entry) return res.status(404).json({ error: 'Digest not found' });

    // Load profile for name
    const { data: profile } = await supabase
      .from('digest_profiles')
      .select('name')
      .eq('id', entry.digest_profile_id)
      .single();

    // Load channels
    const { data: channels } = await supabase
      .from('digest_channels')
      .select('*')
      .eq('digest_profile_id', entry.digest_profile_id)
      .eq('is_active', true);

    const results: Record<string, string> = {};
    const deliveredChannels = [...(entry.channels_delivered || [])];

    // Process each channel (optionally filtered)
    const activeChannels = (channels || []).filter((ch: any) =>
      !channelFilter || channelFilter.includes(ch.channel_type)
    );

    for (const channel of activeChannels) {
      if (channel.channel_type === 'email') {
        const address = channel.channel_config?.address;
        if (!address) {
          results.email = 'No email address configured';
          continue;
        }

        const { subject, html } = formatDigestEmail(entry.content, profile?.name || 'Digest');
        const { success, error } = await sendEmail(address, subject, html);

        if (success) {
          results.email = 'delivered';
          if (!deliveredChannels.includes('email')) deliveredChannels.push('email');
        } else {
          results.email = `failed: ${error}`;
        }
      }

      if (channel.channel_type === 'telegram') {
        const botToken = channel.channel_config?.bot_token;
        const chatId = channel.channel_config?.chat_id;
        if (!botToken || !chatId) {
          results.telegram = 'Bot token or chat ID not configured';
          continue;
        }

        const text = formatDigestTelegram(entry.content, profile?.name || 'Digest');
        const { success, error } = await sendTelegram(botToken, chatId, text);

        if (success) {
          results.telegram = 'delivered';
          if (!deliveredChannels.includes('telegram')) deliveredChannels.push('telegram');
        } else {
          results.telegram = `failed: ${error}`;
        }
      }

      if (channel.channel_type === 'slack') {
        const webhookUrl = channel.channel_config?.webhook_url;
        if (!webhookUrl) {
          results.slack = 'Webhook URL not configured';
          continue;
        }

        const payload = formatDigestSlack(entry.content, profile?.name || 'Digest');
        const { success, error } = await sendSlack(webhookUrl, payload);

        if (success) {
          results.slack = 'delivered';
          if (!deliveredChannels.includes('slack')) deliveredChannels.push('slack');
        } else {
          results.slack = `failed: ${error}`;
        }
      }
    }

    // Update delivery status
    await supabase
      .from('digest_history')
      .update({
        channels_delivered: deliveredChannels,
      })
      .eq('id', history_id);

    return res.status(200).json({ success: true, results });

  } catch (error) {
    console.error('Delivery error:', error);
    return res.status(500).json({
      error: error instanceof Error ? error.message : 'Internal server error',
    });
  }
}
